### ISSUE TITLE
How to reproduce your results shown in your paper, especially Table 1

### ISSUE THREAD

**Issue by shunyuzh** [bozheng-hit/xTune#1]
Hi folks,

Thanks for your sharing awesome tuning methods. I have run your code on MLQA task, just keeping all hyperparams as your setting, also on TESLA V100 32GB. I ran it for 4 random seeds and average them.

```
# run stage 1 of xTune
bash ./scripts/train.sh translate-train-all mlqa xlm-roberta-large 1
# run stage 2 of xTune (optional)
bash ./scripts/train.sh translate-train-all mlqa xlm-roberta-large 2

```

However, I got the lower results than F1/EM=75.0/57.1 in your papers. My results as follows: 
Stage 1: F1=73.50, EM=55.28; 
Stage 2: F1=73.68, EM=55.73

So do you have any idea about it? And if there are something should be noticed?

**Comment by bozheng-hit** [comment]
There was a small bug in the scripts for xlmr-large and now it is fixed.
The expected two-stage results should be 74.3/56.1 and 74.9/57.0 on average.

**Comment by shunyuzh** [comment]
I think there is another question that when running xlmr-large, it should be changed in [line](https://github.com/bozheng-hit/xTune/blob/b2dd0750a089a4297b28e0e1ea5e524a2826bf53/src/run_tag.py#L1194).

No offense, but I suggest that you firstly should reproduce your results by your opensource version.

**Comment by shunyuzh** [comment]
> There was a small bug in the scripts for xlmr-large and now it is fixed.
> The expected two-stage results should be 74.3/56.1 and 74.9/57.0 on average.


Hi, would you like to show other tasks' first stage results of XLMR-lagre in Table 1, including XNLI PAWS-X POS NER XQuAD MLQA TyDiQA. Just like your said 74.3/56.1 and 74.9/57.0 on MLQA.

It's important for me to check if there are BUG in first stage.

Thanks very much.

**Comment by bozheng-hit** [comment]
> I think there is another question that when running xlmr-large, it should be changed in [line](https://github.com/bozheng-hit/xTune/blob/b2dd0750a089a4297b28e0e1ea5e524a2826bf53/src/run_tag.py#L1194).
> 
> No offense, but I suggest that you firstly should reproduce your results by your opensource version.

The base and large-sized models share the same SentencePiece tokenizer, so I don't think this is a bug.
